//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni_II_Kristina_Garcia_Francisco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClinicDoctor
    {
        public int DoctorID { get; set; }
        public int UniqueNumber { get; set; }
        public int BankAccount { get; set; }
        public string Department { get; set; }
        public string WorkingShift { get; set; }
        public bool ReceivingPatient { get; set; }
        public int ManagerID { get; set; }
        public int UserID { get; set; }
    
        public virtual tblClinicManager tblClinicManager { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
