//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nedeljni_II_Kristina_Garcia_Francisco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClinic
    {
        public int ClinicID { get; set; }
        public string ClinicName { get; set; }
        public System.DateTime CreatingDate { get; set; }
        public string ClinicOwner { get; set; }
        public string ClinicAddress { get; set; }
        public int ClinicFloorNumber { get; set; }
        public int RoomsPerFloor { get; set; }
        public bool Balcony { get; set; }
        public bool Garden { get; set; }
        public int EmergencyVehicleParkingLoots { get; set; }
        public int InvalidVehicleParkingLoots { get; set; }
    }
}
